version: '3.8'

services:
  mysqldb:
    container_name: database
    image: 'mysql'
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: liv2train
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3333:3306'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  app:
    image: liv2train:2.1
    build:
      context: ./Liv2Train
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/liv2train?autoReconnect=true&allowPublicKeyRetrieval=true&&useSSL=false
    depends_on:
      mysqldb:
        condition: service_healthy

